@startuml .BBショップ注文管理システム
' ドメインモデル

class お客様 {
  +名前
  +生年月日
  +住所
  +電話番号
  +メールアドレス
  +パスワード
  +注文履歴()
  +ログイン()
  +ログアウト()
}

class 商品 {
  +商品コード
  +商品名
  +在庫管理()
}

class 注文 {
  +注文番号
  +お問い合わせ番号
  +注文日
  +発送準備()
  +発送通知()
  +返金対応()
}

class 管理者 {
  +管理者ID
  +名前
  +メールアドレス
  +パスワード
  +顧客一覧確認()
  +注文一覧確認()
  +発送準備()
  +発送通知()
  +返金対応処理()
  +問い合わせ一覧確認()
  +問い合わせ返信()
  +商品追加()
  +在庫管理()
  +入荷通知()
  +売上確認()
  +配送処理()
  +クレジットカード決済処理()
  +ログイン()
  +ログアウト()
}

class ジャンル {
  +缶バッジ
  +アクリルスタンド
  +フィギュア
  +ポスター
  +カード
  +ぬいぐるみ
  +その他()
}

class クレジットカード情報 {
  +カード番号
  +有効期限
  +名義人
  +セキュリティコード
  +クレカ決済()
}

class 運送会社 {
}

class クレジットカード会社 {
  +会社名
}

' 関係
お客様 -- クレジットカード情報 : 所持
お客様 -- 注文 : 注文履歴
注文 -- 商品 : 商品選択
注文 -- クレジットカード情報 : 支払い
注文 -- 運送会社 : 配送
クレジットカード情報 -- クレジットカード会社 : 発行
ジャンル -- 商品 : 分類

@enduml