@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

[BBシステム] o-- [名前]
[BBシステム] o-- [生年月日]
[BBシステム] o-- [住所]
[BBシステム] o-- [電話番号]
[BBシステム] o-- [メールアドレス]
[BBシステム] o-- [パスワード]
[BBシステム] o-- [注文履歴]
[BBシステム] o-- [ログイン]
[BBシステム] o-- [ログアウト]

[商品] o-- [商品コード]
[商品] o-- [商品名]
[商品] o-- [在庫管理]

[注文] o-- [注文番号]
[注文] o-- [お問い合わせ番号]
[注文] o-- [注文日]
[注文] o-- [発送準備]
[注文] o-- [発送通知]
[注文] o-- [返金対応]

[クレジットカード情報] o-- [カード番号]
[クレジットカード情報] o-- [有効期限]
[クレジットカード情報] o-- [名義人]
[クレジットカード情報] o-- [クレカ決済]

[お客様] -- [注文履歴] : 注文履歴
[注文] -- [商品] : 商品選択
[注文] -- [クレジットカード情報] : 支払い
[注文] -- [運送会社] : 配送
[クレジットカード情報] -- [クレジットカード会社] : 発行

@enduml