@startuml Robodogドメインモデル図
skinparam componentStyle rectangle

[お客様] o-- [名前]
[お客様] o-- [生年月日]
[お客様] o-- [住所]
[お客様] o-- [電話番号]
[お客様] o-- [メールアドレス]
[お客様] o-- [パスワード]
[お客様] o-- [ログイン]
[お客様] o-- [ログアウト]

[商品] o-- [商品コード]
[商品] o-- [商品名]
[商品] o-- [在庫管理]

[注文] o-- [注文番号]
[注文] o-- [お問い合わせ番号]
[注文] o-- [注文日]
[注文] o-- [発送準備]
[注文] o-- [返金対応]

[発送] o-- [注文]

[クレジットカード情報] o-- [名義人]
[クレジットカード情報] o-- [クレカ決済]

[決済履歴] o-- [注文]
[決済履歴] o-- [クレジットカード情報]
[決済履歴] o-- [決済日時]
[決済履歴] o-- [決済金額]
[決済履歴] o-- [決済ステータス]

[お客様] -- [注文履歴] : 注文履歴
[注文] -- [商品] : 商品選択
[注文] -- [クレジットカード情報] : 支払い
[注文] -- [運送会社] : 配送
[クレジットカード情報] -- [クレジットカード会社] : 発行

@enduml