@startuml  
left to right direction
actor 顧客
actor 運送会社
actor カード会社


rectangle   注文管理システム {
顧客 --> (ログイン)
顧客 --> (ログアウト)
顧客 --> (商品を選択)
顧客 --> (カートに追加 / 商品の購入)
顧客 --> (注文履歴の閲覧)
顧客 --> (返金のリクエスト)


(商品の購入) --> (クレジットカード決済)
(商品の購入) --> (在庫管理)
(商品の購入) --> (商品発送の準備)
(在庫管理) --> 運送会社
(商品発送完了の通知) --> 顧客


(クレジットカード決済) --> カード会社
}
@enduml